### ISSUE TITLE
Changes in Create an Article page

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#12]
In the Create an Article page of the Community or Group, we can replace "Create an Article in Community" with ****Community Name>Create an Article**** option in small font above the title of the article. And also, in place of "Article Image" we can have the words "Upload file" or "Upload image" displayed below the body section in the Create an Article page.

**Comment by shaswatam** [comment]
For the second concern, there can be an "Upload media" option in case in future uploading gif or video is allowed.

**Comment by fresearchgroup** [comment]
Done. Please close after verifying
