### ISSUE TITLE
Change of Role

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#150]
Notification - N7, N8, N10
Issue: Message of the notifications
Description: The message should read
N7: Your role has been upgraded from Author to Publisher
N8: Your role has been upgraded from Author to Admin
N10: Your role has been upgraded from Publisher to Admin

**Comment by firuza** [comment]
Done. Close after verification.

**Comment by shaswatam** [comment]
Verified.
