### ISSUE TITLE
Removal of Members

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#151]
Notification No: N13, N14, N15
Issue: Message of the notification
Description: The message should read as
N13: You have been removed from the community. You can no longer contribute
N14: You have been removed from the community. You can no longer contribute
N15: You have been removed from the community. You can no longer contribute

**Comment by firuza** [comment]
Article is available for editing to group members

**Comment by shaswatam** [comment]
Verified.
