### ISSUE TITLE
Unsubscription from the community

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#152]
Notification No: N17, N18, N19
Issue: Message of the notification
Description: The message should read as
N17: You have successfully unsubscribed from the community. You can no longer contribute
N18: You have successfully unsubscribed from the community. You can no longer contribute
N19: You have successfully unsubscribed from the community. You can no longer contribute

**Comment by firuza** [comment]
Article is available for editing to group members

**Comment by shaswatam** [comment]
Verified.
