### ISSUE TITLE
Adding a member to community

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#153]
Issue: No notification
Description: When an Admin adds a member to the community, a notification to the added member should be displayed. The message should read as 'You have been added to the community.'

**Comment by tusharayyar91** [comment]
This issue also follows for groups.
Issue: No notification
Description: When an Admin adds a member to the group, a notification to the added member should be displayed. The message should read as 'You have been added to the group.'

**Comment by firuza** [comment]
Resolved: 'you have been added to the community'

**Comment by firuza** [comment]
When an admin adds a member to the group, an invitation is sent to the user which the user can see under 'My Invitations'. Hence, ignoring the message for group notification.

**Comment by shaswatam** [comment]
Verified.
