### ISSUE TITLE
Adding a member with a specified role

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#154]
Issue: No notification
Description: When an Admin adds a member to the community in the role of a Publisher or an Admin, a notification to the added member should be displayed. The message should read as 'You have been added to the community as a Publisher/ as an Admin.' 
Also, the community feed should display 'Publisher/Admin has been added.'

**Comment by tusharayyar91** [comment]
This issue also follows for groups.
Issue: No notification
Description: When an Admin adds a member to the group in the role of a Publisher or an Admin, a notification to the added member should be displayed. The message should read as 'You have been added to the group as a Publisher/ as an Admin.'
Also, the group feed should display 'Publisher/Admin has been added.'

**Comment by firuza** [comment]
resolved for community. See issue [153](https://github.com/fresearchgroup/Collaboration-System/issues/153)

**Comment by tusharayyar91** [comment]
Verified.
