### ISSUE TITLE
Unsubscription from the group

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#158]
Notification No: N31, N32, N33
Issue: Message of the notification
Description: The message should read as
N31: You have successfully unsubscribed from the group. You can no longer contribute
N32: You have successfully unsubscribed from the group. You can no longer contribute
N33: You have successfully unsubscribed from the group. You can no longer contribute

**Comment by firuza** [comment]
Done. Close after verification.

**Comment by shaswatam** [comment]
Verified.
