### ISSUE TITLE
Removal of Members from a Group

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#160]
Notification No: N40, N41, N42
Issue: Message of the notification
Description: The message should read as
N40: You have been removed from the group. You can no longer contribute
N41: You have been removed from the group. You can no longer contribute
N42: You have been removed from the group. You can no longer contribute

**Comment by firuza** [comment]
Done. Close after verification.

**Comment by shaswatam** [comment]
Verified.
