### ISSUE TITLE
Change of Roles in a Group

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#161]
Notification - N34, N35, N37
Issue: Message of the notifications
Description: The message should read
N34: Your role has been upgraded from Group Author to Group Publisher
N35: Your role has been upgraded from Group Author to Group Admin
N37: Your role has been upgraded from Group Publisher to Group Admin

**Comment by firuza** [comment]
Done. Close after verification.

**Comment by shaswatam** [comment]
Verified.
