### ISSUE TITLE
Group Visible Article not showing in Community Content

### ISSUE THREAD

**Issue by shaswatam** [fresearchgroup/Collaboration-System#20]
Issue: Article created in Group and made visible is not showing in Community content.
Priority: Medium-high

**Comment by firuza** [comment]
Done. A new tab is added called 'Group Content' on 'Community View' page. Kindly verify whether articles having state as visible from all groups of that community are getting displayed or not.

Pending Issue: The group name is not appearing. Close this issue only after the group name also appears along with Article title, created at, etc.

**Comment by firuza** [comment]
Group name appearing. Kindly verify
