### ISSUE TITLE
Published article not showing in my dashboard

### ISSUE THREAD

**Issue by tusharayyar91** [fresearchgroup/Collaboration-System#22]
Page: My dashboard
Issue: I had created an article titled "What is Money?" by the username "tusharayyar@1991" in the Numismatics community which was published by the publisher, but that particular article is not displayed on my dashboard. It is wrongly shown in the user profile of the user named "manas" irrespective of the fact that he is neither the author nor a member of the said community. 
Priority: High/Medium

**Comment by firuza** [comment]
We feel that this was changed by someone from django admin interface (backend). Please let us know incase you notice such an issue for future articles
