### ISSUE TITLE
Non-acceptance of alphabets/symbols in the Request Community form

### ISSUE THREAD

**Issue by shaswatam** [fresearchgroup/Collaboration-System#24]
Page: request_community_creation
Issue: The 'Tag line' bar is not supporting the use of symbols. Also, the 'Purpose' box is not supporting more than one word. When typing a second word error message is shown saying 'Only alphanumeric content are allowed'.
Priority: Medium-high

**Comment by abhisgithub** [comment]
symbols are not allowed . Please close the issue
