### ISSUE TITLE
Forums tab is not functional

### ISSUE THREAD

**Issue by shaswatam** [fresearchgroup/Collaboration-System#30]
Page: Forum/forum
Issue: The Forums tab fetches an error message. [Page not found:404]
Priority: Medium-high

**Comment by firuza** [comment]
- Can view the forum by clicking the 'Forum' tab 
Pending issue:
- Cannot navigate by clicking 'View' and other related buttons, from 'forum' page to community page.

**Comment by shaswatam** [comment]
Resolved.
