### ISSUE TITLE
Add some symbols to the Tag line bar of Community request form

### ISSUE THREAD

**Issue by shaswatam** [fresearchgroup/Collaboration-System#34]
Page: request_community_creation
Issue: Add the following symbols to the "Tag line" bar in the community request form.
          1. !
          2. &
          3. ( )
          4. : 
          5. " "
          6. -
Priority: Medium

**Comment by abhisgithub** [comment]
Feature added.  But in place of " " coma only '   ' comas are allowed

**Comment by shaswatam** [comment]
ok.
